# -*- coding: utf-8 -*-
"""Arithmetic operators.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zhHEXIxnix8wfp7I3SdZHNibbgTtJSzs
"""

#Input two numbers from the user
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))

#Perform arithmetic operations

addition = num1 + num2

subtraction = num1 - num2

multiplication = num1 * num2

division = num1 / num2

integer_division = num1 // num2

remainder = num1 % num2

exponentiation = num1 ** num2

#Display the results print("Addition:", addition)

print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)
print("Integer Division:", integer_division)
print("Remainder:", remainder)
print("Exponentiation:", exponentiation)