# -*- coding: utf-8 -*-
"""Conditional Statements and Loops

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zhHEXIxnix8wfp7I3SdZHNibbgTtJSzs
"""

#IF STATEMENT

age = 18
if age >= 18:
  print("You are an adult.")
else:
  print("You are not an adult.")

# ELIF AND ELSE

#Input the user's age

age=int(input("Enter your age: "))

#Conditional statements

if age < 18:
  print("You are a minor.")
elif age >= 18 and age < 60:
  print("You are an adult.")
else:
  print("You are a senior citizen.")

# FOR LOOP


fruits = ["apple", "banana", "cherry"]
for fruit in fruits:
  print(fruit)

#WHILE LOOP


count = 0
while count < 5:
  print(count)
  count +=1