# -*- coding: utf-8 -*-
"""Logical operators

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zhHEXIxnix8wfp7I3SdZHNibbgTtJSzs
"""

#Input two Boolean values from the user

bool1= bool(input("Enter the FIRST Boolean value (True or False): "))
bool2= bool(input("Enter the second Boolean value (True or False): "))

#Perform Logical operations

logical_and = bool1 and bool2

logical_or = bool1 or boo12

logical_not1 = not bool1
logical_not2 = not bool2

#Display the results

print("Logical AND:", logical_and)

print("Logical OR:", logical_or)
print("Logical NOT (for bool1):", logical_not1)

print("Logical NOT (for bool2):", logical_not2)